// Generated by gencpp from file patrol_robot/pc_to_stm.msg
// DO NOT EDIT!


#ifndef PATROL_ROBOT_MESSAGE_PC_TO_STM_H
#define PATROL_ROBOT_MESSAGE_PC_TO_STM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace patrol_robot
{
template <class ContainerAllocator>
struct pc_to_stm_
{
  typedef pc_to_stm_<ContainerAllocator> Type;

  pc_to_stm_()
    : on_off(false)
    , front_lwheel_target_velocity(0.0)
    , front_rwheel_target_velocity(0.0)
    , back_lwheel_target_velocity(0.0)
    , back_rwheel_target_velocity(0.0)  {
    }
  pc_to_stm_(const ContainerAllocator& _alloc)
    : on_off(false)
    , front_lwheel_target_velocity(0.0)
    , front_rwheel_target_velocity(0.0)
    , back_lwheel_target_velocity(0.0)
    , back_rwheel_target_velocity(0.0)  {
    }



   typedef uint8_t _on_off_type;
  _on_off_type on_off;

   typedef float _front_lwheel_target_velocity_type;
  _front_lwheel_target_velocity_type front_lwheel_target_velocity;

   typedef float _front_rwheel_target_velocity_type;
  _front_rwheel_target_velocity_type front_rwheel_target_velocity;

   typedef float _back_lwheel_target_velocity_type;
  _back_lwheel_target_velocity_type back_lwheel_target_velocity;

   typedef float _back_rwheel_target_velocity_type;
  _back_rwheel_target_velocity_type back_rwheel_target_velocity;




  typedef boost::shared_ptr< ::patrol_robot::pc_to_stm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::patrol_robot::pc_to_stm_<ContainerAllocator> const> ConstPtr;

}; // struct pc_to_stm_

typedef ::patrol_robot::pc_to_stm_<std::allocator<void> > pc_to_stm;

typedef boost::shared_ptr< ::patrol_robot::pc_to_stm > pc_to_stmPtr;
typedef boost::shared_ptr< ::patrol_robot::pc_to_stm const> pc_to_stmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::patrol_robot::pc_to_stm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::patrol_robot::pc_to_stm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace patrol_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'patrol_robot': ['/home/exbot/catkin_ws/src/patrol_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::patrol_robot::pc_to_stm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrol_robot::pc_to_stm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrol_robot::pc_to_stm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f769d436e0706f52db6cef6a616b590e";
  }

  static const char* value(const ::patrol_robot::pc_to_stm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf769d436e0706f52ULL;
  static const uint64_t static_value2 = 0xdb6cef6a616b590eULL;
};

template<class ContainerAllocator>
struct DataType< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "patrol_robot/pc_to_stm";
  }

  static const char* value(const ::patrol_robot::pc_to_stm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on_off\n\
float32 front_lwheel_target_velocity\n\
float32 front_rwheel_target_velocity\n\
float32 back_lwheel_target_velocity\n\
float32 back_rwheel_target_velocity\n\
";
  }

  static const char* value(const ::patrol_robot::pc_to_stm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on_off);
      stream.next(m.front_lwheel_target_velocity);
      stream.next(m.front_rwheel_target_velocity);
      stream.next(m.back_lwheel_target_velocity);
      stream.next(m.back_rwheel_target_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pc_to_stm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::patrol_robot::pc_to_stm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::patrol_robot::pc_to_stm_<ContainerAllocator>& v)
  {
    s << indent << "on_off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on_off);
    s << indent << "front_lwheel_target_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.front_lwheel_target_velocity);
    s << indent << "front_rwheel_target_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.front_rwheel_target_velocity);
    s << indent << "back_lwheel_target_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.back_lwheel_target_velocity);
    s << indent << "back_rwheel_target_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.back_rwheel_target_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATROL_ROBOT_MESSAGE_PC_TO_STM_H
