"""autogenerated by genpy from patrol_robot/pc_to_stm.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pc_to_stm(genpy.Message):
  _md5sum = "f769d436e0706f52db6cef6a616b590e"
  _type = "patrol_robot/pc_to_stm"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool on_off
float32 front_lwheel_target_velocity
float32 front_rwheel_target_velocity
float32 back_lwheel_target_velocity
float32 back_rwheel_target_velocity

"""
  __slots__ = ['on_off','front_lwheel_target_velocity','front_rwheel_target_velocity','back_lwheel_target_velocity','back_rwheel_target_velocity']
  _slot_types = ['bool','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       on_off,front_lwheel_target_velocity,front_rwheel_target_velocity,back_lwheel_target_velocity,back_rwheel_target_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pc_to_stm, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.on_off is None:
        self.on_off = False
      if self.front_lwheel_target_velocity is None:
        self.front_lwheel_target_velocity = 0.
      if self.front_rwheel_target_velocity is None:
        self.front_rwheel_target_velocity = 0.
      if self.back_lwheel_target_velocity is None:
        self.back_lwheel_target_velocity = 0.
      if self.back_rwheel_target_velocity is None:
        self.back_rwheel_target_velocity = 0.
    else:
      self.on_off = False
      self.front_lwheel_target_velocity = 0.
      self.front_rwheel_target_velocity = 0.
      self.back_lwheel_target_velocity = 0.
      self.back_rwheel_target_velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4f.pack(_x.on_off, _x.front_lwheel_target_velocity, _x.front_rwheel_target_velocity, _x.back_lwheel_target_velocity, _x.back_rwheel_target_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.on_off, _x.front_lwheel_target_velocity, _x.front_rwheel_target_velocity, _x.back_lwheel_target_velocity, _x.back_rwheel_target_velocity,) = _struct_B4f.unpack(str[start:end])
      self.on_off = bool(self.on_off)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4f.pack(_x.on_off, _x.front_lwheel_target_velocity, _x.front_rwheel_target_velocity, _x.back_lwheel_target_velocity, _x.back_rwheel_target_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.on_off, _x.front_lwheel_target_velocity, _x.front_rwheel_target_velocity, _x.back_lwheel_target_velocity, _x.back_rwheel_target_velocity,) = _struct_B4f.unpack(str[start:end])
      self.on_off = bool(self.on_off)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4f = struct.Struct("<B4f")
