(cl:in-package patrol_robot-msg)
(cl:export '(ON_OFF-VAL
          ON_OFF
          FRONT_LWHEEL_TARGET_VELOCITY-VAL
          FRONT_LWHEEL_TARGET_VELOCITY
          FRONT_RWHEEL_TARGET_VELOCITY-VAL
          FRONT_RWHEEL_TARGET_VELOCITY
          BACK_LWHEEL_TARGET_VELOCITY-VAL
          BACK_LWHEEL_TARGET_VELOCITY
          BACK_RWHEEL_TARGET_VELOCITY-VAL
          BACK_RWHEEL_TARGET_VELOCITY
))